config/routes.rb
Rails.application.routes.draw do
  get 'contents/', to: 'contents#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'contents#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'static_pages#index', as: :unauthenticated_root
    end
  end

  resources :users, only: :index
  resources :auths, only: %i[index edit update destroy]
end

app/models/auth.rb
class Auth < ApplicationRecord
  validates :user_id,      presence: true
  validates :uid,          presence: true
  validates :provider,     presence: true
  validates :token,        presence: true
  validates :secret_token, presence: true
  validates :destination,  inclusion: { in: [true, false] }

  belongs_to :user

  def self.find_by_omniauth(auth)
    find_by(provider: auth[:provider], uid: auth[:uid])
  end

  def self.create_from_omniauth(user_id, auth)
    case auth[:provider]
    when 'google'
      create(user_id: user_id,
             provider: auth[:provider],
             uid: auth[:uid],
             token: auth[:credentials][:token],
             secret_token: auth[:credentials][:refresh_token],
             expires_at: auth[:credentials][:expires_at],
             save_path: 'savoriter/media')

    when 'twitter'
      create(user_id: user_id,
             provider: auth[:provider],
             uid: auth[:uid],
             token: auth[:credentials][:token],
             secret_token: auth[:credentials][:secret])
    else
      logger.error("Unknown providr:#{auth[:provider]} user_id:#{user_id}")
      nil
    end
  end

  def self.where_medias(user_id)
    Auth.where(user_id: user_id).where.not(provider: 'google')
  end

  def self.find_strage(user_id)
    Auth.where(user_id: user_id, destination: true)[0]
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auth, only: %i[edit update destroy]

  def index
    @auths = Auth.where(user_id: current_user.id)
  end

  def edit; end

  def update
    respond_to do |format|
      if @auth.update(auth_params)
        format.html { redirect_to auths_path, notice: '連携情報を更新しました。' }
        format.json { render :index, status: :ok, location: @auth }
      else
        format.html { render :edit }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @auth.destroy
    respond_to do |format|
      format.html { redirect_to auths_path, notice: '連携情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private

  def set_auth
    @auth = Auth.find(params[:id])
  end

  def auth_params
    params.require(:auth).permit(:destination, :save_path)
  end
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/views/auths/_destination.html.slim
.destination
  - if auth.present?
    ul
      li
        .destination
          |  保存先: 
          - if auth.destination
            |  ✓ 
          - else
            |  ☐ 
      li
        .save_path
          |  保存先パス: 
          = auth.save_path
    ul.auth-edit
      li
        = link_to '編集する', edit_auth_path(auth.id), class: 'btn btn-default'

app/views/auths/_form.html.slim
= form_with(model: auth,local: true) do |form|
  - if auth.errors.any?
    #error_explanation
      h2
        = pluralize(auth.errors.count, "error")
        |  prohibited this auth from being saved:
      ul
        - auth.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label '保存する'
    = form.check_box :destination, id: :destination
    = form.label '保存パス'
    = form.text_field :save_path, id: :save_path, size: '40',
    -                         placeholder: auth.save_path
  .actions
    = form.submit '更新', class: 'btn btn-default'

app/views/auths/_info.html.slim
.auth-cooperation
  .row
    - if auth.present?
      = link_to '連携を解除する', auth, method: :delete,
      -                                   class: 'btn btn-danger',
      -                                   data: {confirm: "本当に解除してもいいですか？"}
    - else
      = link_to '連携する', method("user_#{provider}_omniauth_authorize_path").call,
      -                               class: 'btn btn-primary'

app/views/auths/edit.html.slim
.container
  - if notice
    p#notice.alert.alert-success
      = notice
  - if alert
    p#notice.alert.alert-danger
      = alert
  h1
    = @auth.provider
    | 情報 編集
  = render 'form', auth: @auth
  .back-link
    = link_to 'Back', auths_path

app/views/auths/index.html.slim
.container
  - if notice
    p#notice.alert.alert-success
      = notice
  - if alert
    p#notice.alert.alert-danger
      = alert
  h1
    | 外部連携情報
  - #controllerでやったほうがいいか？
  - auths = @auths.map{ |auth|
  -     case auth.provider
  -     when 'twitter'; [:twitter, auth]
  -     when 'google'; [:google, auth]
  -     end
  -   }.to_h
  .row
    .auth.twitter-auth
      .label.label-default
        |  twitter 
      .auth-body
        ul
          li.col-md-6

          li.col-md-3
            = render 'auths/info', auth: auths[:twitter], provider: 'twitter'
    .auth.google-auth
      .label.label-default
        |  google 
      .auth-body
        ul
          li.col-md-6
            = render 'auths/destination', auth: auths[:google], provider: 'google'
          li.col-md-3
            = render 'auths/info', auth: auths[:google], provider: 'google'
  .back-link
    - #= link_to 'Back', users_path