config/routes.rb
Rails.application.routes.draw do
  get 'contents/', to: 'contents#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: {
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'contents#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'static_pages#index', as: :unauthenticated_root
    end
  end

  resources :users, only: :index
  resources :auths, only: %i[index edit update destroy]
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Savoriter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#gnavi"]
            span.sr-only
              | Bootstrap
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand[href="/"]
            | Savoriter 
        #gnavi.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to "一覧", contents_path
          ul.nav.navbar-nav.nav-session
            - if signed_in?
              li
                = link_to "Profile", auths_path
              li
                = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              li
                = link_to "Sign up", new_user_registration_path
              li
                = link_to "Sign in", new_user_session_path
    - flash.each do |key, value|
      = content_tag(:div, value, class: "#{key}")
    = yield
    footer.footer
      .container
        p.text-muted
          | savoriter